---
abstract: 'PDL binding to the GSL (GNU Scientific Libray) Random Distribution functions'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  PDL: 2.006
  YAML: 0.84
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-GSL-Randist
no_index:
  directory:
    - t
    - inc
requires:
  PDL: 2.006
version: 0.03
